CREATE DATABASE cms_2601;

USE cms_2601;

CREATE TABLE user
(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL
);

CREATE TABLE login
(
email VARCHAR(50) PRIMARY KEY,
user_name VARCHAR(50) NOT NULL,
password VARCHAR(100) NOT NULL,
user_id INT NOT NULL UNIQUE,
FOREIGN KEY(user_id) REFERENCES user(id)
);