CREATE DATABASE IF NOT EXISTS cms_2601;
USE cms_2601;
CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS login (
    email VARCHAR(50) PRIMARY KEY,
    user_name VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    user_id INT NOT NULL UNIQUE,
    FOREIGN KEY(user_id) REFERENCES user(id)
);
CREATE TABLE IF NOT EXISTS lead (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fname VARCHAR(50),
    lname VARCHAR(50),
    contact_no CHAR(10),
    user_id INT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES user(id)
);